version: '3.7'

services:
  rbac-module:
    container_name: rbac-module
    command: npm run test:e2e
    build:
      context: ./docker
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/app